import jeap.tree as tree
import jeap.nodes as nodes

def test_base(node_tree):
    # 2 + 2 * 4^2 / 2 - 1
    et = tree.ExpressionTree()
    literal_two = nodes.ExpressionLiteralNode(2, node_tree)
    literal_four = nodes.ExpressionLiteralNode(4, node_tree)
    literal_one = nodes.ExpressionLiteralNode(1, node_tree)
    aon = nodes.AddOperatorNode(node_tree)
    mon = nodes.MultiplyOperatorNode(node_tree)
    eon = nodes.ExponentOperatorNode(node_tree)
    don = nodes.DivideOperatorNode(node_tree)
    son = nodes.SubtractOperatorNode(node_tree)
    et.add(literal_two)
    et.add(aon)
    et.add(literal_two)
    et.add(mon)
    et.add(literal_four)
    et.add(eon)
    et.add(literal_two)
    et.add(don)
    et.add(literal_two)
    et.add(son)
    et.add(literal_one)
    et.close()
    assert et.evaluate() == 17

def test_boolean_expression(node_tree):
    # (True or False) and not (False)
    et = tree.ExpressionTree()
    gn_one_tree = tree.ExpressionTree()
    gn_one = nodes.GroupNode(node_tree, gn_one_tree)
    gn_two_tree = tree.ExpressionTree()
    gn_two = nodes.GroupNode(node_tree, gn_two_tree)
    eln_true = nodes.ExpressionLiteralNode(True, node_tree)
    eln_false_one = nodes.ExpressionLiteralNode(False, node_tree)
    eln_false_two = nodes.ExpressionLiteralNode(False, node_tree)
    oon = nodes.OrOperatorNode(node_tree)
    aon = nodes.AndOperatorNode(node_tree)
    nn = nodes.NegateNode(node_tree)
    et.add(gn_one)
    et.add(eln_true)
    et.add(oon)
    et.add(eln_false_one)
    et.close()
    et.add(aon)
    et.add(nn)
    et.add(gn_two)
    et.add(eln_false_two)
    et.close()
    et.close()
    assert et.evaluate() == True
